site_title = "MyArxiv"
limit_days = 7
cache_url = "https://mlnlp-world.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "quant-ph"
title = "Quantum Physics"

[[sources]]
limit = 150
category = "physics.atom-ph"
title = "Atomic Physics"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
